language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - mkdir bootstrap/cache
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit
